inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - '**/config.ru'
    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/